"""Add lecturer verification fields and relationships

Revision ID: 7007edb5b1cf
Revises: b104dce063d9
Create Date: 2026-08-05 21:26:35.047191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7007edb5b1cf'
down_revision = 'b104dce063d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_document', sa.String(length=500), nullable=True))

    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('verification_document', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.drop_column('verification_document')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.drop_column('verification_document')

    # ### end Alembic commands ###
