"""Add recommendation_settings table

Revision ID: b104dce063d9
Revises: e819db0f15d6
Create Date: 2026-07-21 18:41:42.657107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b104dce063d9'
down_revision = 'e819db0f15d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('collaborative_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_settings')
    # ### end Alembic commands ###
